/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign Up
         * @description Register a new user.
         *
         *     Args:
         *         signup_data: Email and password
         *         db: Supabase client
         *
         *     Returns:
         *         User and session data
         */
        post: operations["sign_up_api_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign In
         * @description Sign in an existing user.
         *
         *     Args:
         *         signin_data: Email and password
         *         db: Supabase client
         *
         *     Returns:
         *         User and session data with tokens
         */
        post: operations["sign_in_api_auth_signin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign Out
         * @description Sign out the current user.
         *
         *     Args:
         *         user_id: Current user ID from auth token
         *         db: Supabase client
         *
         *     Returns:
         *         Success message
         */
        post: operations["sign_out_api_auth_signout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Info
         * @description Get current user information.
         *
         *     Args:
         *         user_id: Current user ID from auth token
         *         db: Supabase client
         *
         *     Returns:
         *         User profile data
         */
        get: operations["get_current_user_info_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study-plans/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Study Plan
         * @description Generate a new study plan for a user.
         *
         *     Args:
         *         plan_data: Study plan creation data (scores, test date)
         *         user_id: User ID from authentication token
         *         db: Database client
         *
         *     Returns:
         *         Generated study plan with sessions
         */
        post: operations["generate_study_plan_api_study_plans_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study-plans/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Study Plan
         * @description Get the active study plan for the current user.
         *
         *     Args:
         *         user_id: User ID from authentication token
         *         db: Database client
         *
         *     Returns:
         *         Active study plan with all sessions and topics
         */
        get: operations["get_study_plan_api_study_plans_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study-plans/sessions/{session_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session Questions
         * @description Get all questions for a specific practice session.
         *
         *     Args:
         *         session_id: Practice session ID
         *         user_id: User ID from authentication token
         *         db: Database client
         *
         *     Returns:
         *         Session questions with full question details
         */
        get: operations["get_session_questions_api_study_plans_sessions__session_id__questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study-plans/sessions/{session_id}/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Submit Answer
         * @description Submit an answer for a question in a practice session.
         *
         *     Args:
         *         session_id: Practice session ID
         *         question_id: Question ID
         *         answer_data: User's answer and status
         *         user_id: User ID from authentication token
         *         db: Database client
         *
         *     Returns:
         *         Answer correctness and correct answer
         */
        patch: operations["submit_answer_api_study_plans_sessions__session_id__questions__question_id__patch"];
        trace?: never;
    };
    "/api/study-plans/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Categories And Topics
         * @description Get all categories and topics for reference.
         *
         *     Returns:
         *         Categories and topics grouped by section
         */
        get: operations["get_categories_and_topics_api_study_plans__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CategoriesAndTopicsResponse
         * @description Response model for categories and topics
         */
        CategoriesAndTopicsResponse: {
            /** Math */
            math: Record<string, never>;
            /** Reading Writing */
            reading_writing: Record<string, never>;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PracticeSession
         * @description Practice session model
         */
        PracticeSession: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Study Plan Id
             * Format: uuid
             */
            study_plan_id: string;
            /**
             * Scheduled Date
             * Format: date
             */
            scheduled_date: string;
            /** Session Number */
            session_number: number;
            /** Status */
            status: string;
            /**
             * Topics
             * @default []
             */
            topics: components["schemas"]["SessionTopic"][];
        };
        /**
         * Question
         * @description Question model
         */
        Question: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Stem */
            stem: string;
            /** Difficulty */
            difficulty: string;
            /** Question Type */
            question_type: string;
            /** Answer Options */
            answer_options?: Record<string, never> | unknown[] | null;
            /** Correct Answer */
            correct_answer?: string[] | null;
        };
        /**
         * SessionQuestion
         * @description Session question with details
         */
        SessionQuestion: {
            /**
             * Session Question Id
             * Format: uuid
             */
            session_question_id: string;
            question: components["schemas"]["Question"];
            topic: components["schemas"]["Topic"];
            /** Status */
            status: string;
            /** Display Order */
            display_order: number;
            /** User Answer */
            user_answer?: string[] | null;
        };
        /**
         * SessionQuestionsResponse
         * @description Response model for session questions
         */
        SessionQuestionsResponse: {
            /** Session */
            session: Record<string, never>;
            /** Questions */
            questions: components["schemas"]["SessionQuestion"][];
            /** Total Questions */
            total_questions: number;
        };
        /**
         * SessionTopic
         * @description Session topic with question count
         */
        SessionTopic: {
            /**
             * Topic Id
             * Format: uuid
             */
            topic_id: string;
            /** Topic Name */
            topic_name: string;
            /** Num Questions */
            num_questions: number;
        };
        /** SignInRequest */
        SignInRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** SignUpRequest */
        SignUpRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * StudyPlan
         * @description Complete study plan model
         */
        StudyPlan: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * Test Date
             * Format: date
             */
            test_date: string;
            /** Current Math Score */
            current_math_score: number;
            /** Target Math Score */
            target_math_score: number;
            /** Current Rw Score */
            current_rw_score: number;
            /** Target Rw Score */
            target_rw_score: number;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Sessions
             * @default []
             */
            sessions: components["schemas"]["PracticeSession"][];
        };
        /**
         * StudyPlanCreate
         * @description Request model for creating a study plan
         * @example {
         *       "current_math_score": 500,
         *       "current_rw_score": 520,
         *       "target_math_score": 700,
         *       "target_rw_score": 680,
         *       "test_date": "2025-05-01"
         *     }
         */
        StudyPlanCreate: {
            /**
             * Current Math Score
             * @description Current Math score (200-800)
             */
            current_math_score: number;
            /**
             * Target Math Score
             * @description Target Math score (200-800)
             */
            target_math_score: number;
            /**
             * Current Rw Score
             * @description Current Reading/Writing score (200-800)
             */
            current_rw_score: number;
            /**
             * Target Rw Score
             * @description Target Reading/Writing score (200-800)
             */
            target_rw_score: number;
            /**
             * Test Date
             * Format: date
             * @description SAT test date
             */
            test_date: string;
        };
        /**
         * StudyPlanResponse
         * @description Response model for study plan
         */
        StudyPlanResponse: {
            study_plan: components["schemas"]["StudyPlan"];
            /** Total Sessions */
            total_sessions: number;
            /** Total Days */
            total_days: number;
            /** Sessions Per Day */
            sessions_per_day: number;
        };
        /** SubmitAnswerRequest */
        SubmitAnswerRequest: {
            /** User Answer */
            user_answer: string[];
            /**
             * Status
             * @default answered
             */
            status: string;
        };
        /**
         * SubmitAnswerResponse
         * @description Response model for submitting an answer
         */
        SubmitAnswerResponse: {
            /** Is Correct */
            is_correct: boolean;
            /** Correct Answer */
            correct_answer?: string[] | null;
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /**
             * Session Question Id
             * Format: uuid
             */
            session_question_id: string;
        };
        /**
         * Topic
         * @description Topic model
         */
        Topic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Weight In Category */
            weight_in_category: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sign_up_api_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_in_api_auth_signin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_out_api_auth_signout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_current_user_info_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    generate_study_plan_api_study_plans_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyPlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_study_plan_api_study_plans_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyPlanResponse"];
                };
            };
        };
    };
    get_session_questions_api_study_plans_sessions__session_id__questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionQuestionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_answer_api_study_plans_sessions__session_id__questions__question_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitAnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_categories_and_topics_api_study_plans__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriesAndTopicsResponse"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
